version: 2

updates:
  - package-ecosystem: docker
    directories:
      - /jenkins
      - /jenkins-agent
      - /kali
      - /nfs-server
      - /pihole
      - /secrets-manager
      - /transmission
      - /workstation
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(deps)
    groups:
      docker-deps:
        patterns:
          - "*"
