# https://docs.balena.io/reference/supervisor/docker-compose
version: '2'

volumes:
  caddy_config:
  caddy_data:
  secrets:
    driver: local
    driver_opts:
      type: tmpfs
      o: size=1M
      device: tmpfs

services:
  secrets-manager:
    # image: bh.cr/g_stanislav_bebej/secrets-manager
    build: secrets-manager
    environment:
      SECRETS_YML: |
        summon.files:
          - path: /secrets/Caddyfile
            format: template
            overwrite: true
            secrets:
              DNS_NAME: cam-bernolakovo.bebej.dedyn.io
              REXY: http://192.168.66.5:57779
            template: |
              {{ secret "DNS_NAME" }} {
                tls {
                  dns desec {
                    token "{$DESEC_TOKEN}"
                  }
                  propagation_delay 300s
                }
                reverse_proxy {{ secret "REXY" }}
              }
    restart: unless-stopped
    volumes:
      - secrets:/secrets

  caddy:
    build: caddy
    cap_add:
      - NET_ADMIN
    depends_on:
      - secrets-manager
    environment:
      CADDY_FILE_PATH: /secrets/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - secrets:/secrets
