# https://docs.balena.io/reference/supervisor/docker-compose
version: '2'

volumes:
  caddy_config:
  caddy_data:
  secrets:
    driver: local
    driver_opts:
      type: tmpfs
      o: size=1M
      device: tmpfs

services:
  secrets-manager:
    image: bh.cr/g_stanislav_bebej/secrets-manager
    environment:
      SECRETS_YML: |
        summon.files:
          - path: /secrets/Caddyfile
            format: template
            overwrite: true
            secrets:
              DESEC_TOKEN: !var 40d01052-44e9-4a1d-ae3b-b4c800c52703
              MESSAGE: "Hello, world!"
            template: |
              caddy.bebej.dedyn.io {
                tls {
                  dns desec {
                    token "{{ secret "DESEC_TOKEN" }}"
                  }
                  propagation_delay 300s
                }
                respond "{{ secret "MESSAGE" }}"
              }
    volumes:
      - secrets:/secrets

  caddy:
    build: caddy
    cap_add:
      - NET_ADMIN
    depends_on:
      - secrets-manager
    environment:
      CADDY_FILE_PATH: /secrets/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - secrets:/secrets
