name: Block secrets-manager

on:
  push:
    branches:
      - main
    paths:
      - secrets-manager/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    secrets: inherit
    uses: $/.github/workflows/deploy.yml
    with:
      fleet: g_stanislav_bebej/secrets-manager
      project: secrets-manager
